import { WateringCanHolder } from "../../../../assets"

import { ISalesHits } from "../../types/index"

export const AuctionItemsData: ISalesHits[] = [
  {
    id: 0,
    img: WateringCanHolder,
    title: "Держатель для лейки BOOU PG605 Держатель для лейки BOOU PG605..",
    price: "1294 с",
    discount: "1294 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
  {
    id: 1,
    img: WateringCanHolder,
    title: "Держатель для лейки BOOU PG605",
    price: "999999 с",
    discount: "999999 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
  {
    id: 2,
    img: WateringCanHolder,
    title: "Держатель для лейки",
    price: "1294 с",
    discount: "1294 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
  {
    id: 3,
    img: WateringCanHolder,
    title: "Держатель для лейки BOOU PG605",
    price: "1294 с",
    discount: "1294 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
  {
    id: 4,
    img: WateringCanHolder,
    title: "Держатель для лейки BOOU PG605",
    price: "1294 с",
    discount: "1294 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
  {
    id: 5,
    img: WateringCanHolder,
    title: "Держатель для лейки BOOU PG605",
    price: "1294 с",
    discount: "1294 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
  {
    id: 6,
    img: WateringCanHolder,
    title: "Держатель для лейки BOOU PG605 Держатель для лейки BOOU PG605..",
    price: "1294 с",
    discount: "1294 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
  {
    id: 7,
    img: WateringCanHolder,
    title: "Держатель для лейки BOOU PG605 Держатель для лейки BOOU PG605..",
    price: "1294 с",
    discount: "1294 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
]
