import { WateringCanHolder } from "../../../../assets"

import { ISalesHits } from "../../types/index"

export const AuctionItemsData: ISalesHits[] = [
  {
    img: WateringCanHolder,
    title: "Держатель для лейки BOOU PG605 Держатель для лейки BOOU PG605..",
    price: "1294 с",
    discount: "1294 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
  {
    img: WateringCanHolder,
    title: "Держатель для лейки BOOU PG605",
    price: "999999 с",
    discount: "999999 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
  {
    img: WateringCanHolder,
    title: "Держатель для лейки",
    price: "1294 с",
    discount: "1294 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
  {
    img: WateringCanHolder,
    title: "Держатель для лейки BOOU PG605",
    price: "1294 с",
    discount: "1294 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
  {
    img: WateringCanHolder,
    title: "Держатель для лейки BOOU PG605",
    price: "1294 с",
    discount: "1294 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
  {
    img: WateringCanHolder,
    title: "Держатель для лейки BOOU PG605",
    price: "1294 с",
    discount: "1294 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
  {
    img: WateringCanHolder,
    title: "Держатель для лейки BOOU PG605 Держатель для лейки BOOU PG605..",
    price: "1294 с",
    discount: "1294 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
  {
    img: WateringCanHolder,
    title: "Держатель для лейки BOOU PG605 Держатель для лейки BOOU PG605..",
    price: "1294 с",
    discount: "1294 с",
    status: "В наличии",
    type: "Комплект",
    quantity: 0,
  },
]
